-- MySQL Script generated by MySQL Workbench
-- Sun Aug 12 19:11:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema noteshare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema noteshare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `noteshare` DEFAULT CHARACTER SET utf8 ;
USE `noteshare` ;

-- -----------------------------------------------------
-- Table `noteshare`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noteshare`.`t_user` (
  `c_id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_email` VARCHAR(320) NOT NULL,
  `c_username` VARCHAR(256) NOT NULL,
  `c_password_hash` VARCHAR(64) NOT NULL,
  `c_password_salt` VARCHAR(64) NOT NULL,
  `c_created` DATETIME NOT NULL DEFAULT NOW(),
  `c_activated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`c_id`),
  UNIQUE INDEX `c_email_UNIQUE` (`c_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noteshare`.`t_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noteshare`.`t_file` (
  `c_id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_type_id` BIGINT(10) UNSIGNED NOT NULL,
  `c_folder_id` BIGINT(10) UNSIGNED NOT NULL,
  `c_title` VARCHAR(256) NOT NULL,
  `c_created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noteshare`.`t_file_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noteshare`.`t_file_type` (
  `c_id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noteshare`.`t_folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noteshare`.`t_folder` (
  `c_id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_parent` BIGINT(10) UNSIGNED NULL DEFAULT NULL,
  `c_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noteshare`.`t_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noteshare`.`t_group` (
  `c_id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noteshare`.`t_user_belongs_to_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noteshare`.`t_user_belongs_to_group` (
  `c_id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_user_id` BIGINT(10) UNSIGNED NOT NULL,
  `c_group_id` BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noteshare`.`t_folder_belongs_to_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noteshare`.`t_folder_belongs_to_user` (
  `c_user_id` BIGINT(10) UNSIGNED NOT NULL,
  `c_folder_id` BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`c_user_id`, `c_folder_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
